import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";
import { CartProvider } from "./context/CartContext";
import { Toaster } from 'react-hot-toast';

import { ClerkProvider } from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/* const navbar = {
  logo: "/logos/digitec.png",
  links: ["Service", "Case study", "About us", "Career", "Blog"],
  buttonText: "Sign up",
  buttonClassname: "button-primary lg:w-60"
} */

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClerkProvider>
          <CartProvider>
            <Navbar/>
            {children}
          </CartProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
